FROM openjdk:21-jdk
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java", \
   "-DDB_URL=${DB_URL}", \
   "-DDB_USERNAME=${DB_USERNAME}", \
   "-DDB_PASSWORD=${DB_PASSWORD}", \
   "-DDB_DDL_AUTO=${DB_DDL_AUTO}", \
   "-DJWT_ISSUER_URI=${JWT_ISSUER_URI}", \
   "-DKEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}", \
   "-DKEYCLOAK_REALM=${KEYCLOAK_REALM}", \
   "-DKEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}", \
   "-DKEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}", \
   "-DKEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}", \
   "-DKEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}", \
   "-jar", "app.jar"]

EXPOSE 3000