FROM openjdk:21-jdk
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar

ENTRYPOINT ["java",
   "-DDB_URL=${DB_URL}",
   "-DDB_USERNAME=${DB_USERNAME}",
   "-DDB_PASSWORD=${DB_PASSWORD}",
   "-DDB_DDL_AUTO=${DB_DDL_AUTO}",
   "-KEYCLOAK_SERVER_URL=${KEYCLOAK_SERVER_URL}",
   "-KEYCLOAK_REALM=${KEYCLOAK_REALM}",
   "-KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}",
   "-KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}",
   "-KEYCLOAK_ADMIN_USERNAME=${KEYCLOAK_ADMIN_USERNAME}",
   "-KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_ADMIN_PASSWORD}",
   "-jar", "app.jar"]

EXPOSE 3000