spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    hibernate:
      ddl-auto: none
    open-in-view: false
    generate-ddl: false
    # OPEN DOC API 설정
    springdoc:
      version: '1.0.0'
      api-docs:
        path: /api-docs
      default-consumes-media-type: application/json
      default-produces-media-type: application/json
      swagger-ui:
        operations-sorter: alpha
        tags-sorter: alpha
        path: /api-docs.html
        disable-swagger-default-url: true
        doc-expansion: full
      paths-to-match:
        - /v1/**